services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: foreign_k_startup
      POSTGRES_PASSWORD: foreign_k_startup
      POSTGRES_DB: foreign_k_startup
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
